---
- name: "Enable forwarding to {{ role }}"
  command: "{{ splunk.exec }} add forward-server {{ item }}:{{ splunk.s2s_port }} -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: false
  become_user: "{{ splunk.user }}"
  with_items: "{{ groups[role] }}"
  when: "role in groups"
  register: forward_status
  until: forward_status.rc == 0 or 'forwarded-server already present' in forward_status.stderr
  failed_when:
    - forward_status.rc != 0
    - "'forwarded-server already present' not in forward_status.stderr"
  retries: "{{ retry_num }}"
  delay: 3
  notify:
    - Restart the splunkd service
  no_log: "{{ hide_password }}"
