---
- name: Update Splunk directory owner
  file:
    path: "{{ splunk.home }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    recurse: yes
  become: false
  become_user: "{{ privileged_user }}"
