---
- name: Determine Splunk default apps
  set_fact:
    default_apps: [ "legacy", "splunk_gdi", "SplunkForwarder", "SplunkLightForwarder", "gettingstarted",
                    "alert_webhook", "splunk_httpinput", "introspection_generator_addon", "user-prefs",
                    "appsbrowser", "framework", "learned", "launcher", "alert_logevent", "sample_app",
                    "splunk_instrumentation", "search", "splunk_archiver", "splunk_monitoring_console",
                    "_splunk_config", "splunk_enterprise_on_docker", "splunk_forwarder_on_docker", "splunk_metrics_workspace" ]

- name: Find all apps
  find:
    paths: "{{ splunk.app_paths.default }}"
    recurse: no
    file_type: directory
  register: new_apps

- name: Determine installed apps
  set_fact:
    installed_apps: "{{ (installed_apps | default([]) + [ item.path | basename ] | difference(default_apps)) | unique }}"
  with_items: "{{ new_apps.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
