---
- name: Create {{ conf_directory }} directory if not existing
  file:
    path: "{{ conf_directory }}"
    state: directory
  when: conf_directory is defined
  become: false
  become_user: "{{ splunk.user }}"

- name: Create {{ conf_file }} if not existing
  copy:
    dest: "{{ conf_directory }}/{{ conf_file }}"
    mode: u=rw,g=,o=
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    content: ""
    force: no

- include_tasks: set_config_stanza.yml
  vars:
    stanza_name: "{{ stanza.key }}"
    stanza_settings: "{{ stanza.value }}"
  when:
    - stanza.value is defined
    - stanza.value
    - (stanza.value | length > 0)
  with_dict: "{{ conf_stanzas }}"
  loop_control:
    loop_var: stanza
