---
# http://docs.splunk.com/Documentation/Splunk/latest/Updating/Configuredeploymentclients

- name: Wait for the deployment server
  include_tasks: wait_for_splunk_instance.yml
  vars:
    splunk_instance_address: "{{ splunk.deployment_server }}"

- name: Set node as deployment client
  command: "{{ splunk.exec }} set deploy-poll {{ splunk.deployment_server }}:{{ splunk.svc_port }} -auth '{{ splunk.admin_user }}:{{ splunk.password }}'"
  become: false
  become_user: "{{ splunk.user }}"
  register: set_deployment_client
  until: set_deployment_client.rc == 0
  changed_when: set_deployment_client.rc == 0
  retries: "{{ retry_num }}"
  delay: 3
  notify:
    - Restart the splunkd service
  ignore_errors: yes
  no_log: "{{ hide_password }}"
