---
- name: Enable HEC services
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/splunk_httpinput/data/inputs/http/http/enable"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    status_code: 200
    timeout: 10
  ignore_errors: true
  when: not splunk.hec_disabled|bool
  no_log: "{{ hide_password }}"

- name: Create new HEC token
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/splunk_httpinput/data/inputs/http"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name=splunk_hec_token&token={{ splunk.hec_token }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 201,409
    timeout: 10
  ignore_errors: true
  register: splunk_hec_input
  no_log: "{{ hide_password }}"

- name: Enable HEC new-token
  command: "{{ splunk.exec }} http-event-collector enable -name splunk_hec_token -uri {{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }} -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: false
  become_user: "{{ splunk.user }}"
  ignore_errors: true
  when: splunk_hec_input.status != 409
  no_log: "{{ hide_password }}"

- name: Enable SSL for HEC new-token
  command: "{{ splunk.exec }} http-event-collector update -uri {{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }} -enable-ssl {{ splunk.hec_enableSSL }} -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: false
  become_user: "{{ splunk.user }}"
  ignore_errors: true
  when: splunk_hec_input.status != 409
  no_log: "{{ hide_password }}"
