---
- name: Run ESS post-install setup
  command: "{{ splunk.exec }} search '| essinstall' -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  no_log: "{{ hide_password }}"
  become: false
  become_user: "{{ splunk.user }}"
  register: essinstall
  changed_when: essinstall.rc == 0
  failed_when: essinstall.rc != 0
  notify:
    - Restart the splunkd service
