# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

# - name: registration.registries.ca
#   version: '1.0.47'
#   description: TODO
#   attributes:
#     registration_id:
#       label_en: Registration ID
#       description_en: Registration/Incorporation Number or Identifying Number
#       required: true
#     registration_date:
#       label_en: Registration Date
#       description_en: Date of Registration, Incorporation, Continuation or Amalgamation
#       required: false
#     registration_expiry_date:
#       label_en: Registration Expiry Date
#       description_en: Date the registration will expire (unless extended)
#       required: false
#     registration_renewal_effective:
#       label_en: Registration Renewal Effective
#       description_en: Date the registration renewal became effective
#       required: false
#     entity_name:
#       label_en: Name
#       description_en: The legal name of entity
#       required: true
#     entity_name_effective:
#       label_en: Name Effective Date
#       description_en: Date current name became effective
#       required: true
#     entity_name_assumed:
#       label_en: Assumed Name
#       description_en: A legal name used by an extraprovincial company when the home jurisdiction name is not available
#       required: false
#     entity_name_assumed_effective:
#       label_en: Assumed Name Effective Date
#       description_en: Date assumed name became effective
#       required: false
#     entity_name_trans:
#       label_en: Translated Name
#       description_en: Entity name translated into another language
#       required: false
#     entity_name_trans_effective:
#       label_en: Translated Name Effective Date
#       description_en: Date translated name became effective
#       required: false
#     entity_status:
#       label_en: Registration Status
#       description_en: Status of the entity (active or historical)
#       required: true
#     entity_status_effective:
#       label_en: Status Effective Date
#       description_en: Date status became effective
#       required: true
#     entity_type:
#       label_en: Registration Type
#       description_en: Type of entity incorporated or registered
#       required: true
#     registered_jurisdiction:
#       label_en: Registered Jurisdiction
#       description_en: The jurisdiction an entity was created in
#       required: false
#     extra_jurisdictional_registration:
#       label_en: Extra-Jurisdictional Registration
#       description_en: Flag to indicate extra-jurisdictional registrations
#       required: false
#     home_jurisdiction:
#       label_en: Home Jurisdiction
#       description_en: Name of home jurisdiction where org is registered
#       required: true
#     effective_date:
#       label_en: Credential Effective Date
#       description_en: Date Credential is effective
#       required: true
#     reason_description:
#       label_en: Credential Issue Reason
#       description_en: Reason for credential issue/update
#       required: false
#     expiry_date:
#       label_en: Credential Expiry Date
#       description_en: Date Credential expired
#       required: true

# - name: address.registries.ca
#   version: '1.0.47'
#   description: TODO
#   attributes:
#     registration_id:
#       label_en: Registration ID
#       description_en: Unique identifer assigned to entity by registrar
#       required: true
#     addressee:
#       label_en: Addressee
#       description_en: Legal and principle name assigned to entity by registrar
#       required: true
#     address_type:
#       label_en: Address Type
#       description_en: Type designator for this address
#       required: true
#     civic_address:
#       label_en: Civic Address
#       description_en: Street number, name, direction, suite, etc.
#       required: true
#     municipality:
#       label_en: Municipality
#       description_en: Name of a recognized municipality
#       required: true
#     province:
#       label_en: Province
#       description_en: Name of recognized sub-national territory
#       required: true
#     postal_code:
#       label_en: Postal Code
#       description_en: Identifier issued by postal agency
#       required: true
#     country:
#       label_en: Country
#       description_en: Name of a recognized national territory
#       required: true
#     address_effective_date:
#       label_en: Address Effective Date
#       description_en: Date current address became/becomes effective
#       required: false
#     effective_date:
#       label_en: Credential Effective Date
#       description_en: Date Credential is effective
#       required: true
#     expiry_date:
#       label_en: Credential Expiry Date
#       description_en: Date Credential expires
#       required: false
#     reason_description:
#       label_en: Credential Issue Reason
#       description_en: Reason for credential issue/update
#       required: false

- name: cannabis-retail-store-licence.lcrb
  version: '1.1.0'
  description: Cannabis Retail Store Licence Issued by Liquor and Cannabis Regulation Branch
  path: /cannabis-retail-store-licence
  cardinality:
    - licence_number
  attributes:
    registration_id:
      description_en: Registration ID
      data_type: text
      required: true
    licence_number:
      label_en: Licence Number
      description_en: Licence Number
      data_type: text
      required: true
    issue_date:
      label_en: Issue Date
      description_en: Issue Date
      data_type: date
      required: true
    effective_date:
      label_en: Effective Date
      description_en: Effective Date
      data_type: date
      required: true
    expiry_date:
      label_en: Expiry Date
      description_en: Expiry Date
      data_type: date
      required: true
    establishment_name:
      label_en: Establishment Name
      description_en: Establishment Name
      data_type: text
      required: true
    civic_address:
      label_en: Civic Address
      description_en: Civic Address
      data_type: text
      required: false
    city:
      label_en: City
      description_en: City
      data_type: text
      required: false
    province:
      label_en: Province
      description_en: Province
      data_type: text
      required: false
    postal_code:
      label_en: Postal Code
      description_en: Postal Code
      data_type: text
      required: false
    country:
      label_en: Country
      description_en: Country
      data_type: text
      required: false
- name: cannabis-marketing-licence.lcrb
  version: '1.1.0'
  description: Cannabis Marketing Licence Issued by Liquor and Cannabis Regulation Branch
  path: /cannabis-marketing-licence
  cardinality:
    - licence_number
  attributes:
    registration_id:
      description_en: Registration ID
      data_type: text
      required: true
    licence_number:
      label_en: Licence Number
      description_en: Licence Number
      data_type: text
      required: true
    issue_date:
      label_en: Issue Date
      description_en: Issue Date
      data_type: date
      required: true
    effective_date:
      label_en: Effective Date
      description_en: Effective Date
      data_type: date
      required: true
    expiry_date:
      label_en: Expiry Date
      description_en: Expiry Date
      data_type: date
      required: true

### eof ###

