default:
  TEMPLATE_PATH: ../templates

  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080

  WALLET_SEED_VONX: 000000-technologies-inc_00000000

  #INDY_GENESIS_URL: http://localhost:9000/genesis

  LEDGER_PROTOCOL_VERSION: "1.6"
  AUTO_REGISTER_DID: false

### eof ###
